ASPLabs2-4/Controllers/CatalogController.cs
using ASPLabs2_4.Models;
using ASPLabs2_4.ViewModels;
using LinqKit;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace ASPLabs2_4.Controllers
{
    public class CatalogController : Controller
    {
        ElectronicContext db = new ElectronicContext();

        public ActionResult Catalog(string searchString, string sort)
        {
            List<Electronic> electronics = db.Electronics.ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                electronics = Search(searchString);
            }

            if (!string.IsNullOrEmpty(sort))
            {
                if (sort == "Имя")
                {
                    electronics = db.Electronics.OrderBy(a=>a.Name).ToList();
                }
                else if (sort == "Производитель")
                {
                    electronics = db.Electronics.OrderBy(a => a.Maker).ToList();
                }
                else if (sort == "Цена")
                {
                    electronics = db.Electronics.OrderBy(a => a.Price).ToList();
                }
            }

            return View(electronics);
        }

        [HttpGet]
        public ActionResult Buy(int? id)
        {
            ViewBag.ElectronicId = id;
            return View();
        }

        [HttpPost]
        public ActionResult Buy(Purchase purchase)
        {
            purchase.Date = DateTime.Now;
            Cart.Cart cart = (Cart.Cart)Session["Cart" + User.Identity.Name];
            if (cart!= null && cart.Lines.Count() > 0)
            {
                foreach (var item in cart.Lines)
                {
                    purchase.ElectronicId = item.Electronic.Id;
                    for (int i = 0; i < item.Quantity; i++)
                    {
                        db.Purchases.Add(purchase);
                        db.SaveChanges();
                    }
                }
                PurchCartViewModel purchCartViewModel = new PurchCartViewModel { Purchase = purchase, Count = cart.Lines.Count() };
                cart.Clear();
                return View("BoughtAll", purchCartViewModel);
            }
            else
            {
                db.Purchases.Add(purchase);
            }
            db.SaveChanges();
            return RedirectToAction("Bought", purchase);
        }

        [HttpGet]
        public ActionResult Bought(Purchase purchase)
        {
            return View(purchase);
        }

        private List<Electronic> Search(string searchString)
        {
            var predicate = PredicateBuilder.New<Electronic>(e => false);


            Category category = db.Categories.FirstOrDefault(a => a.Name == searchString);

            if (category != null)
            {
                predicate.Or(a => a.CategoryId == category.Id);
            }
            predicate.Or(a => a.Name == searchString);
            predicate.Or(a => a.Maker == searchString);
            if (Int32.TryParse(searchString, out int result1))
            {
                predicate.Or(a => a.Price == result1);
            }
            if (DateTime.TryParse(searchString, out DateTime result2))
            {
                predicate.Or(a => a.ReleaseYear == result2);
            }

            return new List<Electronic>(db.Electronics.Where(predicate));

        }
    }
}

ASPLabs2-4/Views/Catalog/Bought.cshtml
@{
    ViewBag.Title = "Bought";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model ASPLabs2_4.Models.Purchase

<h2>Ваш заказ</h2>
<h3>№ заказа @Model.PurchaseId</h3>
<div>
    @Html.DisplayForModel()
</div>

ASPLabs2-4/Views/Catalog/BoughtAll.cshtml
@{
    ViewBag.Title = "BoughtAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model ASPLabs2_4.ViewModels.PurchCartViewModel



<h2>Ваш заказ</h2>
@if (Model.Count > 1)
{
    <h3>№ заказа(ов) @(Model.Purchase.PurchaseId-Model.Count) - @Model.Purchase.PurchaseId</h3>
}
else
{
    <h3>№ заказа @Model.Purchase.PurchaseId</h3>
}



<div>
    @*@Html.DisplayForModel()*@
    <p>Имя</p>
    @Html.DisplayFor(a => a.Purchase.Person)
    <br>
    <br>
    <p>Адрес</p>
    @Html.DisplayFor(a => a.Purchase.Address)
    <br>
    <br>
    <p>Email</p>
    @Html.DisplayFor(a => a.Purchase.Email)
    <br>
    <br>
    <p>Номер телефона</p>
    @Html.DisplayFor(a => a.Purchase.Phone)
    <br>
    <br>
    <p>Форма оплаты</p>
    @Html.DisplayFor(a => a.Purchase.WageType)
    <br />
</div>

ASPLabs2-4/Views/Catalog/Buy.cshtml
@model ASPLabs2_4.Models.Purchase
@{
    ViewBag.Title = "Buy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h3>Форма оформления покупки</h3>
    @*<form method="post" action="">
            <input type="hidden" value="@ViewBag.ElectronicId" name="ElectronicId" />
            <table>
                <tr>
                    <td><p>Введите свое имя </p></td>
                    <td><input type="text" name="Person" /> </td>
                </tr>
                <tr>
                    <td><p>Введите адрес :</p></td>
                    <td>
                        <input type="text" name="Address" />
                    </td>
                </tr>
                <tr><td><input type="submit" value="Отправить" /> </td><td></td></tr>
            </table>
        </form>*@
    @using (Html.BeginForm("Buy", "Catalog", FormMethod.Post))
    {
        <input type="hidden" value="@ViewBag.ElectronicId" name="ElectronicId" />
        <p>Введите свое имя</p>
        @Html.TextBoxFor(m => m.Person)
        @Html.ValidationMessageFor(a => a.Person)
        <br>
        <p>Введите свой адрес</p>
        @Html.TextAreaFor(m => m.Address)
        @Html.ValidationMessageFor(a => a.Address)
        <br>
        <p>Введите Email</p>
        @Html.TextBoxFor(m => m.Email)
        @Html.ValidationMessageFor(a => a.Email)
        <br>
        <p>Введите свой номер телефона</p>
        @Html.TextBoxFor(m => m.Phone)
        @Html.ValidationMessageFor(a => a.Phone)
        <br>
        @*<p>Выберите подарок</p>
            @Html.ListBoxFor(m=>m.Gifts, new MultiSelectList(new string[] { "Сертификат 10 руб", "Сертификат 15 руб", "Купон на скидку 5%", "Купон на скидку 10%" }))
            <br>
            <br>*@
        <p>Выберите форму оплаты</p>
        @Html.RadioButtonFor(m => m.WageType, "Карта")
        <span>Карта</span> <br />
        @Html.RadioButtonFor(m => m.WageType, "Наличные")
        <span>Наличные</span> <br />
        @Html.RadioButtonFor(m => m.WageType, "Наложенным платежом")
        <span>Наложенным платежом</span> <br />
        @Html.ValidationMessageFor(a => a.WageType)
        <br>
        <input type="submit" value="Отправить" />
    }
</div>

ASPLabs2-4/Views/Catalog/Catalog.cshtml
@{
    ViewBag.Title = "Catalog";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@model List<ASPLabs2_4.Models.Electronic>

<div>
    <h3>Распродажа электроники</h3>
    <br>
    <br>
    <form class="form-inline">
        @*<label>Поиск:</label>*@
        @Html.TextBox("searchString")
        <input type="submit" value="Поиск">
    </form>
    <br>
    <form class="form-inline">
        <select name="sort" class="form-control">
            <option>Все</option>
            <option value="Имя">Имя</option>
            <option value="Производитель">Производитель</option>
            <option value="Цена">Цена</option>
        </select>
        @*<label>Поиск:</label>*@
        @*@Html.TextBox("searchString")*@
        <input type="submit" value="Сортировать">
    </form>
    <br>
    <table>
        <tr style="border-bottom: 2px solid gray;">
            <td><p>Название</p></td>
            <td><p>Производитель</p></td>
            <td><p>Картинка</p></td>
            <td><p>Год выпуска</p></td>
            <td><p>Цена</p></td>
            <td></td>
        </tr>
        @foreach (var b in Model)
        {
            <tr>
                <td><p>@b.Name</p></td>
                <td><p>@b.Maker</p></td>
                <td><img width="50" height="50" src="@b.ImagePath" /></td>
                <td><p>@b.ReleaseYear.ToShortDateString()</p></td>
                <td><p>@b.Price</p></td>
                <td><p><a href="/Catalog/Buy/@b.Id">Купить</a></p></td>
                <td><p><a href="/Cart/Add/@b.Id">Добавить в корзину</a></p></td>
            </tr>
        }
    </table>
</div>